# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Erlang/OTP and contributors
image:
  file: .github/dockerfiles/Dockerfile.ubuntu-base
  context: .github
vscode:
  extensions:
    - ms-vscode.cpptools
    - erlang-ls.erlang-ls
